// <auto-generated />
using System;
using AutoArbs.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoArbs.API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20221215214939_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AutoArbs.Domain.Models.Deposit", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deposit_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserEmail");

                    b.ToTable("DepositHistories");
                });

            modelBuilder.Entity("AutoArbs.Domain.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWithdrawal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Email");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Email = "john@gmail.com",
                            Balance = 0m,
                            Bonus = 0m,
                            FirstName = "John",
                            IsActive = false,
                            LastName = "Doe",
                            Password = "John123",
                            TotalBonus = 0m,
                            TotalDeposit = 0m,
                            TotalWithdrawal = 0m
                        },
                        new
                        {
                            Email = "mary@gmail.com",
                            Balance = 50m,
                            Bonus = 0m,
                            FirstName = "Mary",
                            IsActive = false,
                            LastName = "Jane",
                            Password = "mary123",
                            TotalBonus = 0m,
                            TotalDeposit = 0m,
                            TotalWithdrawal = 0m
                        });
                });

            modelBuilder.Entity("AutoArbs.Domain.Models.Withdrawal", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Account_withdrawn_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Withdrawal_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserEmail");

                    b.ToTable("WithdrawalHistories");
                });

            modelBuilder.Entity("AutoArbs.Domain.Models.Deposit", b =>
                {
                    b.HasOne("AutoArbs.Domain.Models.User", null)
                        .WithMany("DepositHistory")
                        .HasForeignKey("UserEmail");
                });

            modelBuilder.Entity("AutoArbs.Domain.Models.Withdrawal", b =>
                {
                    b.HasOne("AutoArbs.Domain.Models.User", null)
                        .WithMany("WithdrawalHistory")
                        .HasForeignKey("UserEmail");
                });

            modelBuilder.Entity("AutoArbs.Domain.Models.User", b =>
                {
                    b.Navigation("DepositHistory");

                    b.Navigation("WithdrawalHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
