// <auto-generated />
using System;
using AutoArbs.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoArbs.API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20221207195409_update_columns")]
    partial class update_columns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoArbs.Domain.Models.Deposit", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserName");

                    b.ToTable("DepositHistories");
                });

            modelBuilder.Entity("AutoArbs.Domain.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserName = "John1",
                            Balance = 0m,
                            Bonus = 0m,
                            Email = "john@gmail.com",
                            FirstName = "John",
                            IsActive = false,
                            LastName = "Doe",
                            Password = "John123"
                        },
                        new
                        {
                            UserName = "Mary1",
                            Balance = 50m,
                            Bonus = 0m,
                            Email = "mary@gmail.com",
                            FirstName = "Mary",
                            IsActive = false,
                            LastName = "Jane",
                            Password = "mary123"
                        });
                });

            modelBuilder.Entity("AutoArbs.Domain.Models.Withdrawal", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<string>("Account_withdrawn_to")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserName");

                    b.ToTable("WithdrawalHistories");
                });

            modelBuilder.Entity("AutoArbs.Domain.Models.Deposit", b =>
                {
                    b.HasOne("AutoArbs.Domain.Models.User", null)
                        .WithMany("DepositHistory")
                        .HasForeignKey("UserName");
                });

            modelBuilder.Entity("AutoArbs.Domain.Models.Withdrawal", b =>
                {
                    b.HasOne("AutoArbs.Domain.Models.User", null)
                        .WithMany("WithdrawalHistory")
                        .HasForeignKey("UserName");
                });

            modelBuilder.Entity("AutoArbs.Domain.Models.User", b =>
                {
                    b.Navigation("DepositHistory");

                    b.Navigation("WithdrawalHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
